name: Node.js CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar código
      uses: actions/checkout@v3
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      with:
        args: -Dsonar.qualitygate.wait=true
    - name: Instalar dependencias
      run: npm install
    - name: Ejecutar pruebas
      run: npm test
    - name: Construir imagen de Docker
      run: docker build -t jorgevalentefragoso/node-app:latest .
    - name: Iniciar sesión en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Enviar imagen de Docker
      run: docker push jorgevalentefragoso/node-app:latest
